language: php

php:
  - 7.0
  - 5.6
  - 5.5

matrix:
  allow_failures:
    - php: 7.0

before_install:
  - pecl install xdebug
  - phpenv rehash
  - phpenv config-rm xdebug.ini

before_script:
  - composer selfupdate

script:
  - ant composer-init
  - ant build

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: info@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
